# Generated by Django 6.0.7 on 2026-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_emailverification_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='traite',
            field=models.BooleanField(default=False, verbose_name="Validée par l'équipe (contact WhatsApp effectué)"),
        ),
    ]
