# Generated by Django 6.0.7 on 2026-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_reservation_traite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('NEUF', 'Neuf / Jamais utilisé'), ('TBE', 'Très bon état'), ('BE', 'Bon état'), ('USG', 'Usagé / Pour pièces')], default='NEUF', max_length=4),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Poids en kg pour le calcul des frais de port', max_digits=6),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='delai_estime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='prix_base',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Frais de prise en charge fixes', max_digits=10),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='prix_par_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Coût additionnel par kilo', max_digits=10),
        ),
    ]
