# Generated by Django 6.0.7 on 2026-07-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_produit_etat_produit_poids_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='transporteur',
        ),
        migrations.AddField(
            model_name='reservation',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.transporteur'),
        ),
    ]
